server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/multipurpose-portal
    username: postgres
    password: '1234'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl_auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
